### PR TITLE
connection_timeout added

### PR DESCRIPTION
**Pull request by marco-buratto**
It requires the pr https://github.com/stormshield/python-SNS-API/pull/2 to be accepted, too.

### CODE REVIEW

**Comment by remip2** [comment]
Hi,

Thanks for the report, what is you main issue with the default timeout of 60s ?

Since the same https connections can be re-used for several urls, the code you propose should not resolve all the cases. I'll propose the patch in a few days.

**Comment by marco-buratto** [comment]
Hi.

A use case: if you change the management interface's IP where you are
connected to, without the patch Ansible remains waiting forever...

In the following example the 12.206 is the management.

- name: "Change management IPv4 address"
  sns_command:
    force_modify: True
    appliance:
      host: *192.168.12.206*
      user: admin
      password: xxxx
      sslverifyhost: False
    script: |
      CONFIG NETWORK INTERFACE ADDRESS UPDATE ifname=in addrnb=0
*address=192.168.12.179* mask=255.255.255.0
      CONFIG NETWORK INTERFACE ACTIVATE
    expect_disconnect: True
    connection_timeout: 10
  delegate_to: localhost
  register: out

Please note that it's the first time ever I'm using Stormshield: if there's
a better way to accomplish what I need (without reaching the end of my days
:-), for sure I'm willing to understand.

However, anyway, *generally I'd like to be able to specify my own timeouts
on network connections*.

Cheers,


-
Marco Buratto
linkedin.com/in/mburatto




Il giorno mer 29 apr 2020 alle ore 16:39 Rémi Pauchet <
notifications@github.com> ha scritto:

**Comment by remip2** [comment]
Hi Marco, 

I've pushed the code with the timeout option for both projects, can you test it and tell me if it solves your issue ?

Thanks,

**Comment by marco-buratto** [comment]
Confirmed working!

-
Marco Buratto
linkedin.com/in/mburatto




Il giorno mer 29 apr 2020 alle ore 19:42 Rémi Pauchet <
notifications@github.com> ha scritto:

**Comment by remip2** [comment]
Thanks Marco!

**Comment by marco-buratto** [comment]
Are we going to expect some pip package (

stormshield.sns.sslclient

) update soon?

-
Marco Buratto
linkedin.com/in/mburatto




Il giorno lun 4 mag 2020 alle ore 10:46 Rémi Pauchet <
notifications@github.com> ha scritto:

**Comment by remip2** [comment]
1.0.1 has just been pushed to pypi.org

**Comment by marco-buratto** [comment]
Cool!!

-
Marco Buratto
linkedin.com/in/mburatto

Il gio 7 mag 2020, 14:20 Rémi Pauchet <notifications@github.com> ha scritto:

**Pull request closed without merging**
